export type Product = {
  id: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  description: string;
  shortDescription: string;
  price: number;
  originalPrice: number;
  discount: number;
  rating: number;
  reviewCount: number;
  image: string;
  stock: number;
  sku: string;
  featured?: boolean;
  bestSeller?: boolean;
  deal?: boolean;
  newArrival?: boolean;
  specifications: Record<string, string>;
  features: string[];
  tags: string[];
};

const images = {
  gpu: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&q=85",
  cpu: "https://images.unsplash.com/photo-1555617778-02518510b9fa?w=800&q=85",
  ram: "https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&q=85",
  ssd: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&q=85",
  monitor:
    "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=85",
  chair:
    "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&q=85",
  keyboard:
    "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=85",
  headset:
    "https://images.unsplash.com/photo-1599669454699-248893623440?w=800&q=85",
  router:
    "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&q=85",
  smart: "https://images.unsplash.com/photo-1558008258-3256797b43f3?w=800&q=85",
  accessory:
    "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&q=85",
};

type ProductSeed = [
  name: string,
  brand: string,
  category: string,
  subcategory: string,
  price: number,
  shortDescription: string,
  image: string,
];

const seeds: ProductSeed[] = [
  [
    "NVIDIA GeForce RTX 5090 Founders Edition 32GB",
    "NVIDIA",
    "Graphics Cards",
    "PC Components",
    1999.99,
    "32GB GDDR7 · PCIe 5.0",
    "/products/graphics-cards/5090.png",
  ],
  [
    "ASUS TUF Gaming GeForce RTX 5080 OC 16GB",
    "ASUS",
    "Graphics Cards",
    "PC Components",
    1099.99,
    "16GB GDDR7 · 4K Ready",
    "/products/graphics-cards/5080asus.png",
  ],
  [
    "GIGABYTE GeForce RTX 5070 Ti Gaming OC 16GB",
    "GIGABYTE",
    "Graphics Cards",
    "PC Components",
    849.99,
    "16GB GDDR7 · DLSS 4",
    "/products/graphics-cards/GIGABYTE GeForce RTX 5070 Ti Gaming OC 16GB.webp",
  ],
  [
    "MSI GeForce RTX 5070 Ventus 3X OC 12GB",
    "MSI",
    "Graphics Cards",
    "PC Components",
    649.99,
    "12GB GDDR7 · Ray tracing",
    "/products/graphics-cards/MSI GeForce RTX 5070 Ventus 3X OC 12GB.webp",
  ],
  [
    "Sapphire Nitro+ Radeon RX 9070 XT 16GB",
    "Sapphire",
    "Graphics Cards",
    "PC Components",
    749.99,
    "16GB GDDR6 · FSR 4",
    "/products/graphics-cards/Saphire.png",
  ],
  [
    "AMD Ryzen 9 9950X 16-Core Desktop Processor",
    "AMD",
    "CPUs",
    "PC Components",
    599.99,
    "16 cores · 5.7GHz boost",
    "/products/cpus/amd-ryzen-9-9950x.png",
  ],
  [
    "AMD Ryzen 7 9800X3D 8-Core Gaming Processor",
    "AMD",
    "CPUs",
    "PC Components",
    469.99,
    "8 cores · 3D V-Cache",
    "/products/cpus/amd-ryzen-7-9800x3d.png",
  ],
  [
    "Intel Core Ultra 9 285K Desktop Processor",
    "Intel",
    "CPUs",
    "PC Components",
    589.99,
    "24 cores · LGA1851",
    "/products/cpus/intelcore9.png",
  ],
  [
    "Intel Core Ultra 7 265K Desktop Processor",
    "Intel",
    "CPUs",
    "PC Components",
    399.99,
    "20 cores · NPU built-in",
    "/products/cpus/intelcore7.png",
  ],
  [
    "ASUS ROG Crosshair X870E Hero Motherboard",
    "ASUS",
    "Motherboards",
    "PC Components",
    699.99,
    "AM5 · WiFi 7 · DDR5",
    "/products/motherboards/crosshair2.png",
  ],
  [
    "MSI MAG X870 Tomahawk WiFi Motherboard",
    "MSI",
    "Motherboards",
    "PC Components",
    259.99,
    "AM5 · WiFi 7 · PCIe 5.0",
    "/products/motherboards/mag.png",
  ],
  [
    "GIGABYTE B650E AORUS Elite X AX ICE Motherboard",
    "GIGABYTE",
    "Motherboards",
    "PC Components",
    219.99,
    "AM5 · DDR5 · WiFi 6E",
    "/products/motherboards/aorus.png",
  ],
  [
    "Corsair Vengeance RGB 32GB DDR5-6000",
    "Corsair",
    "Memory",
    "PC Components",
    480.99,
    "32GB · 6000MT/s · CL30",
    "/products/memory/corsair.png",
  ],
  [
    "G.SKILL Trident Z5 Neo RGB 64GB DDR5-6000",
    "G.SKILL",
    "Memory",
    "PC Components",
    1150.99,
    "64GB · 6000MT/s · AMD EXPO",
    "/products/memory/gskill.png",
  ],
  [
    "Kingston FURY Beast 32GB DDR5-5600",
    "Kingston",
    "Memory",
    "PC Components",
    150.99,
    "32GB · 5600MT/s · CL36",
    "/products/memory/fury.png",
  ],
  [
    "Samsung 9100 PRO 2TB PCIe 5.0 NVMe SSD",
    "Samsung",
    "Storage",
    "PC Components",
    699.0,
    "14,700MB/s · M.2 2280",
    "/products/storage/samsung3.png",
  ],
  [
    "WD_BLACK SN850X 4TB NVMe Gaming SSD",
    "Western Digital",
    "Storage",
    "PC Components",
    589.1,
    "7,300MB/s · Heatsink",
    "/products/storage/sandisk2.png",
  ],
  [
    "Crucial T705 2TB PCIe Gen5 NVMe SSD",
    "Crucial",
    "Storage",
    "PC Components",
    310,
    "14,500MB/s · Gen5",
    "/products/storage/crucial.png",
  ],
  [
    "Seasonic PRIME TX-1000 1000W Titanium PSU",
    "Seasonic",
    "Power Supplies",
    "PC Components",
    440.99,
    "1000W · 80 PLUS Titanium · Fully modular",
    "/products/power-supplies/seasonic.png",
  ],
  [
    "Corsair RM1000x SHIFT 1000W Modular PSU",
    "Corsair",
    "Power Supplies",
    "PC Components",
    189.99,
    "1000W · ATX 3.1 · PCIe 5.1",
    "/products/power-supplies/rm100.png",
  ],
  [
    "NZXT H9 Flow Dual-Chamber ATX Case",
    "NZXT",
    "PC Cases",
    "PC Components",
    159.99,
    "Dual chamber · Airflow · Tempered glass",
    "/products/pc-cases/nzxt.png",
  ],
  [
    "Lian Li O11D EVO RGB Mid-Tower Case",
    "Lian Li",
    "PC Cases",
    "PC Components",
    169.99,
    "Dual chamber · Tempered glass · RGB",
    "/products/pc-cases/lian.png",
  ],
  [
    "NZXT Kraken Elite 360 RGB Liquid Cooler",
    "NZXT",
    "Cooling",
    "PC Components",
    279.99,
    "360mm · AIO · 2.72-inch LCD",
    "/products/cooling/kraken.png",
  ],
  [
    "Noctua NH-D15 G2 CPU Cooler",
    "Noctua",
    "Cooling",
    "PC Components",
    149.99,
    "Dual tower · 8 heatpipes · 140mm fans",
    "/products/cooling/noctua2.png",
  ],
  [
    "ASUS ROG Strix Scar 18 (2025) Gaming Laptop",
    "ASUS",
    "Laptops",
    "Laptops",
    2999.99,
    "Core Ultra 9 · RTX 5090 · 32GB",
    "/products/laptops/asus.png",
  ],
  [
    "Lenovo Legion Pro 7i Gen 10 Gaming Laptop",
    "Lenovo",
    "Laptops",
    "Laptops",
    2399.99,
    "Core Ultra 9 · RTX 5080 · 32GB",
    "/products/laptops/lenovo.webp",
  ],
  [
    "MSI Raider 18 HX AI Gaming Laptop",
    "MSI",
    "Laptops",
    "Laptops",
    2799.99,
    "Core Ultra 9 · RTX 5090 · 18-inch",
    "/products/laptops/msi.webp",
  ],
  [
    "ASUS TUF Gaming A16 Advantage Edition",
    "ASUS",
    "Laptops",
    "Laptops",
    1199.99,
    "Ryzen 9 · RX 7700S · 16GB",
    "/products/laptops/tuf.webp",
  ],
  [
    "Apple MacBook Air 15-inch M4 16GB",
    "Apple",
    "Laptops",
    "Laptops",
    1299.99,
    "M4 · 16GB · 512GB SSD",
    "/products/laptops/mac2.png",
  ],
  [
    "Razer Blade 16 OLED Gaming Laptop",
    "Razer",
    "Laptops",
    "Laptops",
    2699.99,
    "Core Ultra 9 · RTX 5080 · OLED",
    "/products/laptops/razerblade.png",
  ],
  [
    "LG UltraGear 32GS95UE 32-inch OLED Monitor",
    "LG",
    "Monitors",
    "Monitors",
    1199.99,
    "4K · 240Hz · OLED",
    "/products/monitors/LG_UltraGear_32GS95UE_32-inch_OLED_Monitor.png",
  ],
  [
    "Samsung Odyssey OLED G8 32-inch 4K Monitor",
    "Samsung",
    "Monitors",
    "Monitors",
    1099.99,
    "4K · 240Hz · HDR400",
    "/products/monitors/Samsung Odyssey OLED G8 32-inch 4K Monitor.webp",
  ],
  [
    "Alienware AW3423DWF 34-inch QD-OLED",
    "Alienware",
    "Monitors",
    "Monitors",
    899.99,
    "3440x1440 · 165Hz · QD-OLED",
    "/products/monitors/alienware.png",
  ],
  [
    "ASUS ROG Swift PG27UCDM 27-inch 4K OLED",
    "ASUS",
    "Monitors",
    "Monitors",
    1099.99,
    "4K · 240Hz · 0.03ms",
    "/products/monitors/asusmonitor.png",
  ],
  [
    "Dell UltraSharp U3224KB 32-inch Monitor",
    "Dell",
    "Monitors",
    "Monitors",
    1599.99,
    "6K · IPS Black · Thunderbolt",
    "/products/monitors/dell-ultrasharp-32-6k-monitor.png",
  ],
  [
    "Logitech G915 X Lightspeed Wireless Keyboard",
    "Logitech",
    "Keyboards",
    "Peripherals",
    250.99,
    "Low profile · RGB · Wireless",
    "/products/keyboards/logitech.webp",
  ],
  [
    "Razer BlackWidow V4 Pro 75% Mechanical Keyboard",
    "Razer",
    "Keyboards",
    "Peripherals",
    289.99,
    "Hot-swap · RGB · Tactile",
    "/products/keyboards/razer2.png",
  ],
  [
    "Keychron Q1 Max QMK Wireless Keyboard",
    "Keychron",
    "Keyboards",
    "Peripherals",
    200.99,
    "75% · QMK · Wireless",
    "/products/keyboards/keychron.webp",
  ],
  [
    "Corsair K70 MAX RGB Magnetic Keyboard",
    "Corsair",
    "Keyboards",
    "Peripherals",
    240.99,
    "Hall effect · Adjustable actuation",
    "/products/keyboards/corsairkeyboard.webp",
  ],
  [
    "Logitech G Pro X Superlight 2 Mouse",
    "Logitech",
    "Mice",
    "Peripherals",
    159.99,
    "60g · 32K DPI · Wireless",
    "/products/mice/logitechmouse.png",
  ],
  [
    "Razer Viper V3 Pro Wireless Mouse",
    "Razer",
    "Mice",
    "Peripherals",
    149.99,
    "54g · 35K DPI · Wireless",
    "/products/mice/razerviper.png",
  ],
  [
    "SteelSeries Aerox 5 Wireless Mouse",
    "SteelSeries",
    "Mice",
    "Peripherals",
    119.99,
    "9 buttons · Quantum 2.0",
    "/products/mice/steelseriesmouse.png",
  ],
  [
    "Logitech G Pro X 2 LIGHTSPEED Headset",
    "Logitech",
    "Headsets",
    "Peripherals",
    249.99,
    "Graphene drivers · Wireless",
    "/products/headsets/logitechheadset.png",
  ],
  [
    "SteelSeries Arctis Nova Pro Wireless",
    "SteelSeries",
    "Headsets",
    "Peripherals",
    349.99,
    "ANC · Dual wireless",
    "/products/headsets/steelseriesheadset.png",
  ],
  [
    "Razer BlackShark V2 Pro Wireless Headset",
    "Razer",
    "Headsets",
    "Peripherals",
    179.99,
    "HyperClear mic · 70 hours",
    "/products/headsets/razerheadset.png",
  ],
  [
    "Elgato Facecam 4K USB Webcam",
    "Elgato",
    "Webcams",
    "Peripherals",
    199.99,
    "4K60 · HDR · Fixed Focus",
    "/products/webcams/elegatofacecam.png",
  ],
  [
    "Logitech MX Brio Ultra HD Webcam",
    "Logitech",
    "Webcams",
    "Peripherals",
    179.99,
    "4K · HDR · Dual beamforming",
    "/products/webcams/Logitech_MX_Brio_Ultra_HD_Webcam.png",
  ],
  [
    "Xbox Wireless Controller Carbon Black",
    "Xbox",
    "Controllers",
    "Gaming",
    59.99,
    "Bluetooth · Xbox · PC",
    "/products/controllers/xbox.png",
  ],
  [
    "Sony DualSense Wireless Controller",
    "Sony",
    "Controllers",
    "Gaming",
    74.99,
    "Haptic feedback · PS5",
    "/products/controllers/sony2.png",
  ],
  [
    "ASUS ROG Rapture GT-BE98 Pro WiFi 7 Router",
    "ASUS",
    "Networking",
    "Networking",
    699.99,
    "Quad-band · 30Gbps · WiFi 7",
    "/products/networking/asusrog.png",
  ],
  [
    "TP-Link Archer BE800 WiFi 7 Router",
    "TP-Link",
    "Networking",
    "Networking",
    499.99,
    "19Gbps · 10Gb Ethernet",
    "/products/networking/tplink.png",
  ],
  [
    "eero Max 7 Mesh WiFi 7 System 3-Pack",
    "eero",
    "Networking",
    "Networking",
    1699.99,
    "10Gbps · 3-pack · Mesh",
    "/products/networking/eero.png",
  ],
  [
    "NETGEAR MS308 8-Port 2.5G Multi-Gig Switch",
    "NETGEAR",
    "Networking",
    "Networking",
    119.99,
    "8-port · 2.5GbE",
    "/products/networking/netgear.png",
  ],
  [
    "Google Nest Hub Max Smart Display",
    "Google",
    "Smart Home",
    "Smart Home",
    229.99,
    "10-inch · HD display · Smart home control",
    "/products/smart-home/nesthub.png",
  ],
  [
    "Sonos Era 300 Smart Speaker",
    "Sonos",
    "Smart Home",
    "Smart Home",
    449.99,
    "Dolby Atmos · WiFi · Bluetooth",
    "/products/smart-home/sonos.png",
  ],
  [
    "Ring Stick Up Cam Pro Battery Camera",
    "Ring",
    "Smart Home",
    "Smart Home",
    179.99,
    "1080p HDR · Color Night Vision · Battery",
    "/products/smart-home/ringstick.png",
  ],
  [
    "Philips Hue White & Color Ambiance Starter Kit",
    "Philips Hue",
    "Smart Home",
    "Smart Home",
    119.99,
    "Color lighting · Hue Bridge · Smart control",
    "/products/smart-home/philip2.png",
  ],
  [
    "Anker 777 Thunderbolt Docking Station",
    "Anker",
    "Accessories",
    "Accessories",
    249.99,
    "12-in-1 · Thunderbolt 4 · 40Gbps",
    "/products/accessories/anker2.png",
  ],
  [
    "CalDigit TS4 Thunderbolt 4 Dock",
    "CalDigit",
    "Accessories",
    "Accessories",
    379.99,
    "18 ports · 98W charging · 2.5GbE",
    "/products/accessories/caldigit.png",
  ],
  [
    "Anker 737 Power Bank 24K",
    "Anker",
    "Accessories",
    "Accessories",
    109.99,
    "24,000mAh · 140W · Smart display",
    "/products/accessories/anker737.png",
  ],
  [
    "Satechi Dual Vertical Laptop Stand",
    "Satechi",
    "Accessories",
    "Accessories",
    44.99,
    "Aluminum · Dual slot · Adjustable",
    "/products/accessories/satechi.png",
  ],
];

export const products: Product[] = seeds.map(
  (
    [name, brand, category, subcategory, price, shortDescription, image],
    index,
  ) => ({
    id: `tv-${String(index + 1).padStart(3, "0")}`,
    name,
    brand,
    category,
    subcategory,
    shortDescription,
    description: `${name} delivers dependable performance for modern workstations, gaming rigs, and creative setups. This demo listing includes realistic specifications for browsing and cart testing.`,
    price,
    originalPrice: Math.round(price * (1.08 + (index % 4) * 0.04) * 100) / 100,
    discount: Math.round(
      (1 - price / (price * (1.08 + (index % 4) * 0.04))) * 100,
    ),
    rating: Number((4.4 + (index % 6) / 10).toFixed(1)),
    reviewCount: 86 + index * 37,
    image: image.startsWith("/") ? image : images[image as keyof typeof images],
    stock: 4 + (index % 22),
    sku: `TV-${brand.slice(0, 3).toUpperCase()}-${String(index + 100).padStart(4, "0")}`,
    featured: index < 12,
    bestSeller: index % 4 === 0,
    deal: index % 3 === 0,
    newArrival: index % 5 === 0,
    specifications: Object.fromEntries(
      shortDescription.split(" · ").map((part, i) => [`Spec ${i + 1}`, part]),
    ),
    features: [
      "Fast, reliable everyday performance",
      "Designed for modern setups",
      "Backed by a limited demo warranty",
    ],
    tags: [brand, category, subcategory, "tech", "upgrade"],
  }),
);

export const categorySlugs: Record<string, string> = {
  "graphics-cards": "Graphics Cards",
  cpus: "CPUs",
  laptops: "Laptops",
  monitors: "Monitors",
  gaming: "Gaming PCs",
  storage: "Storage",
  memory: "RAM",
  keyboards: "Keyboards",
  mice: "Mice",
  headsets: "Headsets",
  networking: "Networking",
  "smart-home": "Smart Home",
  accessories: "Accessories",
};

export function getProduct(id: string) {
  return products.find((product) => product.id === id);
}
export function searchProducts(query: string) {
  const q = query.toLowerCase();
  return products.filter((p) =>
    [p.name, p.brand, p.category, ...p.tags]
      .join(" ")
      .toLowerCase()
      .includes(q),
  );
}
export function categoryProducts(category: string) {
  return products.filter(
    (p) => p.category === category || p.subcategory === category,
  );
}
